task done
karaaa006/nodejs-homework-template pull request #3
Opened 2022-02-05 15:59 UTC by karaaa006

2022-02-05 19:33 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = authorization.split(" ");
если authorization будет undefined - split() не будет выполнен и выдаст ошибку

2022-02-05 19:36 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const skip = (page - 1) * limit;
рекомендую перед математическими вычислениями делать проверку входящих параметров на число - например через isNaN

2022-02-05 19:41 UTC, KirillKulakow commented on routes/api/contacts.js
>  const express = require("express");
по роутам получения изменения и удаления нет логики конфиденциальности данных контакта
любой зарегистрированный пользователь может получить/удалить/изменить любой контакт
нужно добавить поиск не только по ид контакта но и по ид собственника

2022-02-05 19:43 UTC, KirillKulakow requested changes
Need fix

2022-02-05 20:48 UTC, karaaa006 commented
Все поправил

2022-02-05 22:04 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (String(result.owner) !== req.user.id)
два вопроса
почему нельзя сделать поиск двух сущностей? Например `await Contact.findOne({ _id: ObjectId(req.params.contactId), owner: req.user.id})`
и почему ошибка not Auth - если нужно отдавать что такой контакт не найден?

2022-02-05 22:04 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (String(result.owner) !== req.user.id)
тот же вопрос

2022-02-05 22:05 UTC, KirillKulakow commented on routes/api/contacts.js
>      const removedContact = await Contact.findByIdAndDelete(
здесь можно использовать findOneAndDelete - с фильтром в виде объекта

2022-02-05 22:05 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (String(findedContact.owner) !== req.user.id)
тот же вопрос

2022-02-05 22:06 UTC, KirillKulakow commented on routes/api/contacts.js
> +  if (String(findedContact.owner) !== req.user.id)
тот же вопрос

2022-02-05 22:06 UTC, KirillKulakow commented on routes/api/users.js
> +    console.log(user);
удалить

2022-02-05 22:06 UTC, KirillKulakow commented on routes/api/users.js
> +    console.log(email, password);
удалить

2022-02-05 22:07 UTC, KirillKulakow requested changes
Need refactor

2022-02-06 19:47 UTC, karaaa006 commented on routes/api/contacts.js
> +    if (String(result.owner) !== req.user.id)
Что-то вылетело с головы findOne, спасибо за качественную проверку

2022-02-06 19:53 UTC, KirillKulakow approved these changes

2022-02-07 06:34 UTC, merged