main task done
karaaa006/nodejs-homework-template pull request #4
Opened 2022-02-10 20:12 UTC by karaaa006

2022-02-10 20:54 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
рекомендация
в данной миддлваре можно добавить проверку на тип входящего файла, если есть желание можешь попробовать добавить проверку на изображение

2022-02-10 20:55 UTC, KirillKulakow commented on routes/api/users.js
> +    const avatarURL = gravatar.url(req.body.email);
в данном методе добавь опцию вывода протокола - для того чтобы ссылка на аватар была полной

2022-02-10 20:56 UTC, KirillKulakow commented on routes/api/users.js
> +          avatarURL: path.join("avatars", newFilename),
сделай полную ссылку на аватар - по типу http://localhost:3000/public/avatars/avatar.jpg
чтобы при переходи по данной ссылке твоим приложением была выдана картинка

2022-02-10 20:57 UTC, KirillKulakow approved these changes
Need fix

2022-02-10 20:57 UTC, KirillKulakow requested changes
Need fix

2022-02-13 21:32 UTC, karaaa006 commented on routes/api/users.js
> +          avatarURL: path.join("avatars", newFilename),
Богдан, вроде, говорил что лучше хранить неполный путь, но исправил как ты сказал

2022-02-13 21:32 UTC, karaaa006 commented on routes/api/users.js
> +    const avatarURL = gravatar.url(req.body.email);
Добавил

2022-02-13 21:32 UTC, karaaa006 commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
Сделал проверку

2022-02-14 12:04 UTC, KirillKulakow commented on routes/api/users.js
> +          avatarURL: path.join(avatarsDir, newFilename),
итак, что у тебя будет в итоге
avatarsDir вернет тебе путь внутри твоего компа - Users/admin/GOIT/...
не похоже на необходимую ссылку
я хочу чтобы ты понял как работает отдача статики в node js `app.use(express.static("public"));`

2022-02-14 12:05 UTC, KirillKulakow commented on routes/api/users.js
> +          avatarURL: path.join(avatarsDir, newFilename),
при переходе по ссылке которую ты создал делается поиск файла не твоим приложением, а самим браузером

2022-02-14 12:06 UTC, KirillKulakow requested changes
need fix

2022-05-18 07:45 UTC, merged